### ISSUE TITLE
报错，详情见内

### ISSUE THREAD

**Issue by CberYellowstone** [wopub/Bilibili2Bangumi#8]
> PS D:\Code\Bilibili2Bangumi> python bili2bgm.py
请在弹出的授权页面中点击授权。
若授权页面没有自动弹出，请手动复制链接至浏览器中打开：
https://bgm.tv/oauth/authorize?client_id=bgm184060850037e220f&response_type=code
正在尝试取得授权...
Traceback (most recent call last):
  File "bili2bgm.py", line 44, in <module>
    loop.run_until_complete(main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "bili2bgm.py", line 34, in main
    bgm_auth_data = await auth_bgm_task
  File "D:\Code\Bilibili2Bangumi\auth.py", line 83, in auth_bgm
    f'{bgm_auth_data_raw["token_type"]}'
KeyError: 'token_type'

**Comment by SINC-G** [comment]
这边测试正常。

这输出信息有点对不上，可以尝试更新到最新的commit。

授权信息没获取到，可能是网络问题？可以再尝试多运行几次。

**Comment by CberYellowstone** [comment]
> 这边测试正常。
> 
> 授权信息没获取到，可能是网络问题？可以再尝试多运行几次。

建议加一个手动填写code的功能

**Comment by SINC-G** [comment]
> 建议加一个手动填写code的功能

一开始用的输入，现在监听回调不是更好吗

**Comment by CberYellowstone** [comment]
> > 建议加一个手动填写 code 的功能
> 
> 一开始用的输入，现在监听回调不是更好吗

两个一起可以排除到底是哪个环节问题

**Comment by CberYellowstone** [comment]
@SINC-G 上述bug确认是缓降问题，复现条件不明
新的bug：

> ** 异常被引发！
** aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://api.bgm.tv/subject/26449')
** 3 次尝试均失败，退出！
Traceback (most recent call last):
  File ".\bili2bgm.py", line 44, in <module>
    loop.run_until_complete(main())
  File "C:\Users\28448\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File ".\bili2bgm.py", line 38, in main
    await get_and_update(bili2bgm_map, bili_auth_data, BILI_UID, bgm_auth_data)
  File "C:\Users\28448\Administrator\Temp\Bilibili2Bangumi\update.py", line 241, in get_and_update
    await data.update_bgm_data_task
  File "C:\Users\28448\Administrator\Temp\Bilibili2Bangumi\update.py", line 137, in update_bgm_data
    await gather(*data.update_one_bgm_data_tasks)
  File "C:\Users\28448\Administrator\Temp\Bilibili2Bangumi\update.py", line 70, in update_one_bgm_data
    lambda: client.get(
  File "C:\Users\28448\Administrator\Temp\Bilibili2Bangumi\utilities.py", line 94, in try_for_times_async_json
    depth=depth+1
  File "C:\Users\28448\Administrator\Temp\Bilibili2Bangumi\utilities.py", line 69, in try_for_times_async_chain
    result = await f(result)
  File "C:\Users\28448\AppData\Local\Programs\Python\Python37\lib\site-packages\aiohttp\client_reqrep.py", line 1103, in json
    headers=self.headers,
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://api.bgm.tv/subject/26449')

**Comment by SINC-G** [comment]
@NKID00 麻烦过来看一下

> ** 异常被引发！
** aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://api.bgm.tv/subject/26449')
** 3 次尝试均失败，退出！
Traceback (most recent call last):
File ".\bili2bgm.py", line 44, in
loop.run_until_complete(main())
File "C:\Users\28448\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 587, in run_until_complete
return future.result()
File ".\bili2bgm.py", line 38, in main
await get_and_update(bili2bgm_map, bili_auth_data, BILI_UID, bgm_auth_data)
File "C:\Users\28448\Administrator\Temp\Bilibili2Bangumi\update.py", line 241, in get_and_update
await data.update_bgm_data_task
File "C:\Users\28448\Administrator\Temp\Bilibili2Bangumi\update.py", line 137, in update_bgm_data
await gather(*data.update_one_bgm_data_tasks)
File "C:\Users\28448\Administrator\Temp\Bilibili2Bangumi\update.py", line 70, in update_one_bgm_data
lambda: client.get(
File "C:\Users\28448\Administrator\Temp\Bilibili2Bangumi\utilities.py", line 94, in try_for_times_async_json
depth=depth+1
File "C:\Users\28448\Administrator\Temp\Bilibili2Bangumi\utilities.py", line 69, in try_for_times_async_chain
result = await f(result)
File "C:\Users\28448\AppData\Local\Programs\Python\Python37\lib\site-packages\aiohttp\client_reqrep.py", line 1103, in json
headers=self.headers,
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://api.bgm.tv/subject/26449')

**Comment by NKID00** [comment]
报用json解码html的一般都是被风控挡了然后要人机验证之类的…

要么就是网站服务器抽了

我找找解决方案

**Comment by NKID00** [comment]
试试看调低 `CONNECTION_LIMIT_PER_HOST`（每站点最大并发连接数）？

但是调低之后运行速度可能会慢一点

**Comment by NKID00** [comment]
> 
> 
> 报用json解码html的一般都是被反爬挡了然后要人机验证之类的…
> 
> 要么就是网站服务器抽了
> 
> 我找找解决方案

bgm的api用了cloudflare家自带反爬的cdn就很难受

还是遇到就弹个手动验证人机验证？

**Comment by SINC-G** [comment]
@NKID00 速度慢点可以，只要保证能正确迁移就行。

**Comment by SINC-G** [comment]
话说这反爬机制对我们这种更新也生效嘛，我们也没在爬数据啊，如果是还好，我们还可以用镜像站

**Comment by SINC-G** [comment]
或者由用户选择，一种快速模式，提示可能会触发反爬机制需手动验证，一种稳定模式，速度可能较快速模式更慢。

**Comment by NKID00** [comment]
写了一些调试代码试了下貌似高并发的情况下会被 503

在 503 的时候主动停一会应该就能解决问题了
